[package]
name = "blog"
version = "0.1.0"
edition = "2021"
publish = true

[dependencies]
console_error_panic_hook = "0.1.7"
include_dir = "0.7.4"
mdsycx = { git = "https://github.com/lukechu10/mdsycx", rev = "ca406d1" }
serde = { version = "1.0.210", features = ["derive"] }
sycamore = "0.9.0-beta.3"
sycamore-router = "0.9.0-beta.3"

[patch.crates-io]
sycamore = { git = "https://github.com/sycamore-rs/sycamore", rev = "ba34877" }
